#日常环境

##配置sql打印日志
spring:
  cloud:
    nacos:
      discovery:
        server-addr: pre.nacos-node1.com:8848
  datasource:
    matrix:  # 数据源1
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://pre.leader-mysql.com:3306/matrix?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Hongkong
      username: root
      password: XianYue1998@



















